.TH "idevicedate" 1
.SH NAME
idevicedate \- Display the current date or set it on a device.
.SH SYNOPSIS
.B idevicedate
[OPTIONS]

.SH DESCRIPTION

Simple utility to manage the clock on a device.

.SH OPTIONS
.TP
.B \-d, \-\-debug
enable communication debugging.
.TP
.B \-u, \-\-udid UDID
target specific device by its 40-digit device UDID.
.TP
.B \-s, \-\-set TIMESTAMP
set UTC time described by TIMESTAMP
.TP
.B \-c, \-\-sync
set time of device to current system time
.TP
.B \-h, \-\-help
prints usage information

.SH AUTHOR
Martin Szulecki
