.TH "idevicesyslog" 1
.SH NAME
idevicesyslog \- Relay syslog of a connected device.
.SH SYNOPSIS
.B idevicesyslog
[OPTIONS]

.SH DESCRIPTION

Relay syslog of a connected device.

.SH OPTIONS
.TP 
.B \-d, \-\-debug
enable communication debugging.
.TP
.B \-u, \-\-udid UDID
target specific device by its 40-digit device UDID
.TP 
.B \-h, \-\-help
prints usage information.

.SH AUTHOR
Martin Szulecki

Man page written to conform with Debian by Julien Lavergne.
