.TH "idevicenotificationproxy" 1
.SH NAME
idevicenotificationproxy \- Post or observe notifications on a device.
.SH SYNOPSIS
.B idevicenotificationproxy
[OPTIONS] COMMAND

.SH DESCRIPTION

Post or observe notifications on an iOS device from the command line.

.SH OPTIONS
.TP
.B \-u, \-\-udid UDID
target specific device by its 40-digit device UDID.
.TP
.B \-d, \-\-debug
enable communication debugging.
.TP
.B \-h, \-\-help
prints usage information.

.SH COMMANDS
.TP
.B post ID [ID...]
post notification IDs to device and exit.
.TP
.B observe ID [ID...]
observe notification IDs in the foreground until CTRL+C or signal is received.

.SH AUTHORS

Martin Szulecki

.SH ON THE WEB
http://libimobiledevice.org
