.TH "idevicebackup2" 1
.SH NAME
idevicebackup2 \- Create or restore backups for devices running iOS 4 or later.
.SH SYNOPSIS
.B idevicebackup2
[OPTIONS] CMD [CMDOPTIONS] DIRECTORY

.SH DESCRIPTION

Create or restore backup from the current or specified directory.

.SH OPTIONS
.TP
.B \-u, \-\-udid UDID
target specific device by its 40-digit device UDID.
.TP 
.B \-d, \-\-debug
enable communication debugging.
.TP 
.B \-h, \-\-help
prints usage information.

.SH COMMANDS
.TP
.B backup
create backup for the device.
.TP
.B restore
restore last backup to the device.
.TP
.B \t\-\-system
restore system files, too.
.TP
.BI \t\-\-reboot
reboot the system when done.
.TP
.B \t\-\-copy
create a copy of backup folder before restoring.
.TP
.B \t\-\-settings
restore device settings from the backup.
.TP
.B info
show details about last completed backup of device.
.TP
.B list
list files of last completed backup in CSV format.
.TP
.B unback
unpack a completed backup in DIRECTORY/_unback_/.

.SH AUTHORS
Martin Szulecki

Nikias Bassen

.SH SEE ALSO
idevicebackup(1)
