.TH "idevice_id" 1
.SH NAME
idevice_id \- Prints device name or a list of attached devices.
.SH SYNOPSIS
.B idevice_id
[OPTIONS] [UDID]

.SH DESCRIPTION

Prints device name or a list of attached devices.
The UDID is a 40-digit hexadecimal number of the device
for which the name should be retrieved.

.SH OPTIONS
.TP
.B \-l, \-\-list
list UDID of all attached devices
.TP 
.B \-d, \-\-debug
enable communication debugging.
.TP 
.B \-h, \-\-help
prints usage information.
.TP 

.SH AUTHORS
 Zach C.

 Jonathan Beck

 Matt Colyer

 Martin Aumueller

 Christophe Fergeau

 Martin S.

 Paul Sladen

 Patrick Walton

 Zoltan Balaton

 Nikias Bassen

 Todd Zullinger

Man page written to conform with Debian by Julien Lavergne.
