.TH "ideviceenterrecovery" 1
.SH NAME
ideviceenterrecovery \- Makes a device with the supplied 40-digit UUID enter recovery mode immediately.
.SH SYNOPSIS
.B ideviceenterrecovery
[OPTIONS] UUID

.SH DESCRIPTION

Makes a device with the supplied 40-digit UUID enter recovery mode immediately.

.SH OPTIONS
.TP
.B \-d, \-\-debug
enable communication debugging.
.TP 
.B \-h, \-\-help
prints usage information.

.SH AUTHORS
Martin Szulecki

Man page written to conform with Debian by Julien Lavergne.
