.TH "idevicescreenshot" 1
.SH NAME
idevicescreenshot \- Gets a screenshot from the connected device.
.SH SYNOPSIS
.B idevicescreenshot
[OPTIONS] [FILE]

.SH DESCRIPTION

Gets a screenshot from the connected device.

The screenshot is saved as a TIFF image with the given FILE name, where the
default name is "screenshot-DATE.tiff",
e.g.: ./screenshot-2013-12-31-23-59-59.tiff

NOTE: A mounted developer disk image is required on the device, otherwise
the screenshotr service is not available.

.SH OPTIONS
.TP
.B \-d, \-\-debug
enable communication debugging.
.TP
.B \-u, \-\-udid UDID
target specific device by its 40-digit device UDID.
.TP
.B \-h, \-\-help
prints usage information

.SH AUTHOR
Nikias Bassen

Man page written to conform with Debian by Julien Lavergne.

.SH ON THE WEB
http://libimobiledevice.org
