.TH "ideviceenterrecovery" 1
.SH NAME
ideviceenterrecovery \- Make a device enter recovery mode.
.SH SYNOPSIS
.B ideviceenterrecovery
[OPTIONS] UDID

.SH DESCRIPTION

Makes a device with the supplied 40-digit UDID enter recovery mode immediately.

.SH OPTIONS
.TP
.B \-d, \-\-debug
enable communication debugging.
.TP 
.B \-h, \-\-help
prints usage information.

.SH AUTHORS
Martin Szulecki

Man page written to conform with Debian by Julien Lavergne.

.SH ON THE WEB
http://libimobiledevice.org
